Models/Chef.cs
#pragma warning disable CS8618

using System.ComponentModel.DataAnnotations;
public class Chef
{
    [Key]
    public int ChefId {get; set; }

    [Required]
    [MinLength(2, ErrorMessage = "Insert First Name")]
    public string FirstName {get; set; }

    [Required]
    [MinLength(2, ErrorMessage ="Insert Last Name")]
    public string LastName {get; set; }

    [Required]
    [OverEighteen(ErrorMessage =" Poingo ssa")]
    
    public DateTime BirthDate {get; set; }

    public List<Dish> Dishes {get; set; } = new List<Dish>();
    public DateTime CreatedAt {get; set; } = DateTime.Now;
    public DateTime UpdatedAt {get; set; } = DateTime.Now;
}

Models/DateValidations.cs
using System.ComponentModel.DataAnnotations;
public class DateValidations : ValidationAttribute
{
    protected override ValidationResult IsValid(object value, ValidationContext context)
    {
        DateTime _dateJoin = Convert.ToDateTime(value);
        if (_dateJoin < DateTime.Now)
        {
            return ValidationResult.Success;
        }
        else
        {
            return new ValidationResult("must be 18 years or older");
        }
    }
}

Models/Dish.cs
#pragma warning disable CS8618

using System.ComponentModel.DataAnnotations;

public class Dish
{
    [Key]
    public int DishId{get; set; }

    [Required]
    [MinLength(2, ErrorMessage = "Insert name of dish")]
    public string DishName {get; set; }

    [Required]
    [Range(1, 10000, ErrorMessage = "Please insert calories")]
    public int Calories {get; set; }

    [Required]
    [MinLength(20, ErrorMessage = "Please leave a brief description")]
    public string Description {get; set; }

    [Required]
    [Range(1, 5, ErrorMessage = "Please indicate tastiness")]
    public int Tastiness {get; set; }

    public DateTime CreatedAt {get; set; } = DateTime.Now;
    public DateTime UpdatedAt {get; set; } = DateTime.Now;
    public int ChefId {get; set; }
    public Chef? Creator {get; set; }
}

Models/ErrorViewModel.cs
namespace ChefsAndDishes.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/ORMContext.cs
#pragma warning disable CS8618

using Microsoft.EntityFrameworkCore;
namespace ChefsAndDishes.Models;

public class ORMContext : DbContext
{
    public ORMContext(DbContextOptions options) : base(options){  }

    public DbSet<Dish> Dishes {get;  set; }
    public DbSet<Chef> Chefs {get; set; }
}

Models/OverEighteen.cs
using System.ComponentModel.DataAnnotations;
public class OverEighteen : ValidationAttribute
{
    protected override ValidationResult IsValid(object value, ValidationContext context)
    {
        DateTime _dateJoin = Convert.ToDateTime(value);
        if (_dateJoin.AddYears(18) < DateTime.Now)
        {
            return ValidationResult.Success;
        }
        else
        {
            return new ValidationResult("must be 18 years or older");
        }
    }
}

Controllers/ChefController.cs
using Microsoft.AspNetCore.Mvc;
using ChefsAndDishes.Models;
using Microsoft.EntityFrameworkCore;

public class ChefController : Controller

{
    private ORMContext _context;

    public ChefController(ORMContext context)
    {
        _context = context;
    }

    [HttpGet("/")]
    public IActionResult AllChef()
    {
        List<Chef> allChefs = _context.Chefs.Include(chef => chef.Dishes).ToList();

        return View("AllChef", allChefs);
    }
    [HttpPost("/AddChef")]
    public IActionResult CreateChef(Chef newChef)
    {
        if (ModelState.IsValid == false)
        {
        return View("NewChef");
        }
        else
        {           
        _context.Chefs.Add(newChef);
        _context.SaveChanges();
        
        return RedirectToAction("AllChef");
        }
    }
    [HttpGet("/new")]
    public IActionResult NewChef()
    {
        return View("NewChef");
    }

}

Controllers/DishController.cs
using Microsoft.AspNetCore.Mvc;
using ChefsAndDishes.Models;
using Microsoft.EntityFrameworkCore;

public class DishController : Controller
{
    private ORMContext _context;

    public DishController(ORMContext context)
    {
        _context = context;
    }

    [HttpGet("/dishes")]
    public IActionResult AllDish()
    {
        List<Dish> allDishes = _context.Dishes.Include(dish => dish.Creator).ToList();
        return View("AllDish", allDishes);
    }

    [HttpPost("AddDish")]
    public IActionResult CreateDish(Dish newDish)
    {
        if (ModelState.IsValid == false)
        {
            return AddDish();
        }
        
            _context.Dishes.Add(newDish);
            _context.SaveChanges();
        return RedirectToAction("AllDish");
    }
    
    [HttpGet("/dishes/new")]
    public IActionResult AddDish()
    {
        List<Chef> allChefs = _context.Chefs.ToList();
        ViewBag.allChefs = allChefs;
        return View("NewDish");
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ChefsAndDishes.Models;

namespace ChefsAndDishes.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return RedirectToAction("AllChef", "Chef");
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Chef/AllChef.cshtml
@model List<Chef>

<h2>Chefs | <a href="/dishes"
>Dishes</a></h2>
<p><a href="/new">Add a Chef</a></p>

<h1>Check out our roster of Chefs!</h1>
<table>
<thead>
    <th>Name</th>
    <th>Age</th>
    <th># of Dishes</th>
</thead>

@foreach (Chef chef in Model)
{
    
        
        <tr>
            <td>@chef.FirstName @chef.LastName</td>
            <td>@(DateTime.Now.Year - chef.BirthDate.Year)</td>
            <td>@chef.Dishes.Count</td>
        </tr>

}
    <tbody>
</table>

Views/Chef/NewChef.cshtml
@model Chef

<h1>Add a Chef!</h1>
<div>
<form asp-controller="Chef" asp-action="CreateChef" method = "Post">
    <div>
        <label asp-for="FirstName"></label>
        <span asp-validation-for="FirstName">
        </span>
        <input asp-for="FirstName">
    </div>
        <div>
        <label asp-for="LastName"></label>
        <span asp-validation-for="LastName">
        </span>
        <input asp-for="LastName">
    </div>
        <div>
        <label asp-for="BirthDate"></label>
        <span asp-validation-for="BirthDate"></span>
        <input type="date" asp-for="BirthDate">
        
    </div>
    <input value="Add Chef" type="submit">
</form>
</div>

Views/Dish/AllDish.cshtml
@model List<Dish>

<h2><a href="/">Chefs</a> | Dishes</h2>
<p><a href="/dishes/new">Add a Dish</a></p>

<h1>Take a look at our tasty dishes!</h1>

    <table>
        <thead>
            <tr>
            <th>Name</th>
            <th>Chef</th>
            <th>Tastiness</th>
            <th>Calories</th>
            </tr>
        </thead>
        <tbody>

@foreach (Dish dish in Model)
{

        <tr>
            <td>@dish.DishName</td>
            <td>@dish.Creator.FirstName @dish.Creator.LastName</td>
            <td>@dish.Tastiness</td>
            <td>@dish.Calories</td>
        </tr>
    
    
}
    </tbody>
</table>

Views/Dish/NewDish.cshtml
@model Dish

<h1>Add a Dish</h1>
<div>
    <form asp-controller="Dish" asp-action="CreateDish" method = "Post">
        <div>
        <label asp-for="DishName"></label>
        <span asp-validation-for="DishName">
        </span>
        <input asp-for="DishName">
    </div>
    <div>
        <label asp-for="Calories"></label>
        <span asp-validation-for="Calories">
        </span>
        <input asp-for="Calories">
    </div>
    <div>
        <label asp-for="Description"></label>
        <span asp-validation-for="Description">
        </span>
        <input asp-for="Description">
    </div>
    
    <div>
        <label asp-for="ChefId"></label>
        <span asp-validation-for="ChefId">
        </span>
        <select asp-for="ChefId">
        @foreach(Chef chef in ViewBag.allChefs)
        {
            <option value="@chef.ChefId">@chef.FirstName @chef.LastName</option>
        }
        </select>
    </div>
    <div>
        <label asp-for="Tastiness"></label>
        <span asp-validation-for="Tastiness">
        </span>
        <input asp-for="Tastiness">
    </div>
    <input value="Add Dish" type="submit">
    </form>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChefsAndDishes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ChefsAndDishes.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ChefsAndDishes</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ChefsAndDishes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>